twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/text_custom.html.twig'
        - 'form/datetime_custom.html.twig'
        - 'form/active_custom.html.twig'
        - 'form/money_custom.html.twig'
    debug: '%kernel.debug%'

when@test:
    twig:
        strict_variables: true
