# config/services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Service\TwigService:
        arguments:
            $compRepo: '@App\Repository\EvcComponentsRepository'
        tags:
            - { name: twig.extension }
    App\EventListener\AuthListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }