# config/services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Service\TwigService:
        arguments:
            $compRepo: '@App\Repository\EvcComponentRepository'
        tags:
            - { name: twig.extension }
    
    App\EventListener\AuthListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    App\Service\FormService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
    
    App\Form\Type\OnOffType:
        tags: ['form.type']

    App\Form\Type\SelectType:
        tags: ['form.type']

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        calls:
            - [setAnnotationReader, ['@annotation_reader']]
        tags:
            - { name: doctrine.event_subscriber, connection: default }